---
title: "Wait to enable button"
output: 
    flexdashboard::flex_dashboard:
        orientation: rows
        vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
# converted from Shiny
# https://stackoverflow.com/a/40558301/5270873

library(flexdashboard)
library(shiny)
library(shinyjs)
```

# Inputs {.sidebar}

```{r, echo=FALSE}
numericInput("go_btns_quant","Number of GO buttons",value = 1,min = 1,max = 10)
```

# Page

##

### Column 1

```{r}
uiOutput("go_buttons")

    # to store observers and make sure only once is created per button
    obsList <- list()
    
    output$go_buttons <- renderUI({
        buttons <- as.list(1:input$go_btns_quant)
        buttons <- lapply(buttons, function(i)
        {
            btName <- paste0("go_btn",i)
            # creates an observer only if it doesn't already exists
            if (is.null(obsList[[btName]])) {
                # make sure to use <<- to update global variable obsList
                obsList[[btName]] <<- observeEvent(input[[btName]], {
                    cat("Button ", i, "\n")
                    output$plot <-renderPlot({hist(rnorm(100, 4, 1),breaks = 50*i)})
                })
            }
            fluidRow(
                actionButton(btName,paste("Go",i))
            )
        }
        )
    })
```


### Column 2
```{r}
plotOutput("plot")
```

