---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny    
---

```{r setup, include=FALSE}
library(flexdashboard)
```

# Direct implicit output

## Row

### box

```{r}
basicPage(
  
  h3("Now we have both text and plot output"),
  textInput("mytext", "Input goes here") #,
  
  # my_output_text comes from the server
  # textOutput("my_output_text"),
  
  # my_output_plot comes from the server
  # plotOutput("my_output_plot")
  
)
```

## Row
### box
```{r}
renderText({
    txt <- "Your value is: "
    return(paste0(txt, input$mytext))
  })

```


### box

```{r}
# send plot to the ui as my_output_plot
renderPlot({
    plot(1:10, 1:10, pch=16, col=1:10, cex=1:10, 
         main = input$mytext)
  })
```


# Explicit output

## Row

### box

```{r}
basicPage(
  
  h3("Now we have both text and plot output"),
  textInput("mytext2", "Input goes here") ,
  
  # my_output_text comes from the server
  textOutput("my_output_text2"),
  
  # my_output_plot comes from the server
  plotOutput("my_output_plot2")
)
```

## Row

### box

```{r}
my_output_text2 <- renderText({
    txt2 <- "Your value is: "
    return(paste0(txt2, input$mytext2))
  })

my_output_text2
```


### box

```{r}
# send plot to the ui as my_output_plot
my_output_plot2 <- renderPlot({
    plot(1:10, 1:10, pch=16, col=1:10, cex=1:10, 
         main = input$mytext2)
  })

my_output_plot2
```




