---
title: "Observer demo"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny     
---

```{r setup, include=FALSE}
# R:\r-shiny\shiny-mini-apps\shiny-rstudio\055-observer-demo
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
sliderInput("n", "N:", min = 10, max = 1000, value = 200, step = 10)
```

```{r}
  # Create a random name for the log file
  logfilename <- paste0('logfile',
                        floor(runif(1, 1e+05, 1e+06 - 1)),
                        '.txt')


  # This observer adds an entry to the log file every time
  # input$n changes.
  obs <- observe({    
    cat(input$n, '\n', file = logfilename, append = TRUE)
  })
  

```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderText({
    paste0("The value of input$n is: ", input$n)
  })
```


```{r}
  # When the client ends the session, suspend the observer.
  # Otherwise, the observer could keep running after the client
  # ends the session.
  session$onSessionEnded(function() {
    obs$suspend()

    # Also clean up the log file for this example
    unlink(logfilename)
  })
```


