---
title: "Exercise 05"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny       
---

```{r setup, include=FALSE}
library(flexdashboard)

    # Assignment: This app doesn't work! It's supposed to let
    # the user click on the plot, and have a data point appear
    # where the click occurs. But as written, the data point
    # only appears for a moment before disappearing.
    # 
    # This happens because each time the plot is re-rendered,
    # the value of input$click is reset to NULL, and thus
    # userPoint() becomes NULL as well.
    # 
    # Can you get a single user-added data point to stay?
    # 
    # Bonus points: Can you include not just the single most
    # recent click, but ALL clicks made by the user?
    # 
    # Hint: You'll need to replace reactive() with a combo
    # of reactiveValues() and observeEvent().
```



```{r}

rv <- reactiveValues(userPoint = NULL)

observeEvent(input$click, {
    if (!is.null(input$click)) {
        rv$userPoint <- data.frame(speed = input$click$x, dist = input$click$y)  
    }
})
```


```{r}
renderPlot({
    # Before plotting, combine the original dataset with
    # the user data. (rbind ignores NULL args.)

    df <- rbind(cars, rv$userPoint)
    plot(df, pch = 19)
    
    model <- lm(dist ~ speed, df)
    abline(model)
    })
```

