---
title: ""
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny     
---

```{r setup, include=FALSE}
# Source: https://towardsdatascience.com/get-started-with-examples-of-reactivity-in-in-shiny-apps-db409079dd11

library(flexdashboard)
```


Column {.sidebar}
-----------------------------------------------------------------------
```{r}
textInput("name", "Your Name")
selectInput("age", "Age bracket",c("18-25","25-45","above 45"))
textInput("weight", "Please enter your weight in kg")
textInput("height", "Please enter your height in cm")
actionButton("save", "Add")
```


```{r}
# fields have to be the same as the input names
fields <- c("name", "age", "height", "weight")

# create a data frame called responses
saveData <- function(data) {
    # called by the "Add" button
    data <- as.data.frame(t(data))
    if (exists("responses")) {
        responses <<- rbind(responses, data)
    } else {
        responses <<- data
    }
}

loadData <- function() {
    if (exists("responses")) {
        responses
    }
}

# Whenever a field is filled, aggregate all form data
formData <- reactive({
    data <- sapply(fields, function(x) input[[x]])
    data
})
      
# When the Save/Add button is clicked, save the form data
observeEvent(input$save, {
    saveData(formData())
})
```


Column {data-width=650}
-----------------------------------------------------------------------

### Table A

```{r}
# Show the previous responses
# (update with current response when save is clicked)
DT::renderDataTable({
     input$save
     loadData()
}, editable = TRUE)  # make table editable    
# See more on datatable in https://rstudio.github.io/DT/
```

