---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
runtime: shiny
---




```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)

library(plotly)

library(shiny)

set.seed(1)

airbnb_data = read_csv("./data/nyc_airbnb.zip") %>%
  clean_names() %>%
  mutate(rating = review_scores_location / 2) %>%
  select(boro = neighbourhood_group, neighbourhood, rating, price, room_type,
         latitude, longitude) %>%
  filter(!is.na(rating)) 
## Parsed with column specification:
## cols(
##   id = col_integer(),
##   review_scores_location = col_integer(),
##   name = col_character(),
##   host_id = col_integer(),
##   host_name = col_character(),
##   neighbourhood_group = col_character(),
##   neighbourhood = col_character(),
##   latitude = col_double(),
##   longitude = col_double(),
##   room_type = col_character(),
##   price = col_integer(),
##   minimum_nights = col_integer(),
##   number_of_reviews = col_integer(),
##   last_review = col_date(format = ""),
##   reviews_per_month = col_double(),
##   calculated_host_listings_count = col_integer(),
##   availability_365 = col_integer()
## )
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
boros = airbnb_data %>% distinct(boro) %>% pull()

# selectInput widget
selectInput("boro_choice", label = h3("Select boro"),
            choices = boros, selected = "Manhattan")

renderPrint({ 
  input$boro_choice
})

max_price = 1000
min_price = airbnb_data %>% distinct(price) %>% min()
  
# sliderInput widget
sliderInput("price_range", label = h3("Choose price range"), min = min_price, 
        max = max_price, value = c(100, 400))

room_choice = airbnb_data %>% distinct(room_type) %>% pull()

# radioButtons widget
radioButtons("room_choice", label = h3("Choose room type"),
    choices = room_choice, 
    selected = "Entire home/apt")
```


Row
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlotly({
    airbnb_data %>%
    filter(boro == input$boro_choice, 
           price %in% input$price_range[1]:input$price_range[2],
           room_type == input$room_choice) %>%
    mutate(text_label = str_c("Price: $", price, '\nRating: ', rating)) %>% 
    plot_ly(x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~price,
          text = ~text_label)
})
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPlotly({
  airbnb_data %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")
})
```

### Chart C

```{r}
renderPlotly({ 
  common_neighborhoods =
    airbnb_data %>% 
    filter(boro == input$boro_choice,
           price %in% input$price_range[1]:input$price_range[2],
           room_type == input$room_choice) %>%
    count(neighbourhood, sort = TRUE) %>% 
    top_n(8) %>% 
    select(neighbourhood)

  airbnb_data %>%
    filter(boro == input$boro_choice,
                          price %in% input$price_range[1]:input$price_range[2],
                          room_type == input$room_choice) %>%
    inner_join(., common_neighborhoods, by = "neighbourhood") %>% 
    plot_ly(y = ~price, color = ~neighbourhood, type = "box",
          colors = "Set2")
  
})
```

